### ISSUE TITLE
これからどういう方針でいきましょうか？

### ISSUE THREAD

**Issue by mino2357** [sk2sat/nbody#1]
リープ・フロッグで精度良くなったのを確認しました．

これから（仕事の息抜きに見て）PRだすぞ～ってことで，これからどういう方針のおつもりでしょう．と聞くissueを立てる．

（１）精度はあまり気にせずで比較的大きい系を見る．
（２）精度いいやつで比較的小さい系を見る．
（３）GPUで殴る（）

（その他）

取り敢えず，skasatのlibraryを含めてrepository単一で動くようにしてみませんか．（私が楽になるので）

（私の夢：相対論の効果入れて近日点移動をシミュレートしたいなぁ．）

**Comment by sk2sat** [comment]
うーん，残念ながらGPUで殴れる環境が無いので3はそもそも無理ですね．．．(そのうちやってみたくはあるけど
1と2で言うと，どちらも興味はあるのですがとりあえずは2をやっていきたいですね．
ありがちですが球状星団とかやってみたいです．
libsksatは色々問題があるのでどうにかしようと思っています．

**Comment by mino2357** [comment]
了解です．その方針でまずは行きましょう．
その前に，libsksatのmathの中のベクトル計算，一般のn次元で計算できるようにしたほうが，のちのち良さそうですね．
そのへんも改善していきますか．
